{
    "seetings":{
        "treeId":"",
        "treeObj":"",
        "code":"",
        "name":"",
        "check":{},
        "async":{}
},
    "data":[{
    "id":"",
    "pid":"",
    "name":"",
    "icon":"节点图标，如果节点展开与关闭图标一致，则传入此属",
    "iconOpen":"展开图标",
    "iconClose":"关闭图标"
},{}]
}